### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by benidene** [WeImproveOurSkill/PayPick#30]
## 어떤 작업인가요?

> Fix, invaild : 좌표 전송 및 매장 리스트 호출 로직이 시큐리티 filter에서 막히는 상황 발생

## 작업 상세 내용

- [x] security 부분 확인 바람

<img width="1160" alt="스크린샷 2024-02-25 오전 7 57 42" src="https://github.com/WeImproveOurSkill/PayPick/assets/111226162/e6ffb790-f61c-49de-98d9-56f3e4b0176d">
<img width="1407" alt="스크린샷 2024-02-25 오전 7 57 27" src="https://github.com/WeImproveOurSkill/PayPick/assets/111226162/0623fd0c-4634-4d38-a3cd-0374ad0d1ce4">
<img width="1406" alt="스크린샷 2024-02-25 오전 7 56 55" src="https://github.com/WeImproveOurSkill/PayPick/assets/111226162/c9740840-9fe1-4dcf-a0f9-a80029f8e690">

**Comment by skyriv213** [comment]
store 리스트 값 반환이 안되는 상황 발생
setHttpheaders no field
